_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": val/dice_metric
              "6":
                - 3
              "7":
                - 2
            - "1": val/sensitivity
              "6":
                - 3
              "7":
                - 2
            - "1": train/loss
              "6":
                - 3
              "7":
                - 1
        python_version: 3.8.3
        t:
            "1":
                - 1
                - 10
                - 11
                - 41
                - 48
                - 49
                - 55
            "2":
                - 1
                - 10
                - 11
                - 41
                - 48
                - 49
                - 55
            "3":
                - 7
                - 13
                - 23
                - 55
                - 63
            "4": 3.8.3
            "5": 0.18.5
            "6": 4.43.0.dev0
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
data:
    value:
        cache_rate: 1
        image: C:\Users\Marina.VALVE\kits23\train_test_split_50\images
        label: C:\Users\Marina.VALVE\kits23\train_test_split_50\labels
        num_class: 2
        num_workers: 2
        root_dir: C:\Users\Marina.VALVE\kits23\train_test_split_50
log:
    value:
        name: CalyxSegmentationNet
        save_dir: C:\Users\Marina.VALVE\GitHub\UNET_Kidney_Segmentation\weights
loss:
    value:
        monai.losses.DiceCELoss:
            args: []
            kwargs:
                softmax: true
                to_onehot_y: true
net:
    value:
        monai.networks.nets.UNet:
            args: []
            kwargs:
                channels:
                    - 16
                    - 32
                    - 64
                    - 128
                    - 256
                in_channels: 1
                norm: BATCH
                num_res_units: 2
                out_channels: 2
                spatial_dims: 3
                strides:
                    - 2
                    - 2
                    - 2
                    - 2
train:
    value:
        augmentation:
            - monai.transforms.LoadImaged:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
            - monai.transforms.EnsureChannelFirstd:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
            - monai.transforms.ScaleIntensityRanged:
                args: []
                kwargs:
                    a_max: 164
                    a_min: -57
                    b_max: 1
                    b_min: 0
                    clip: true
                    keys:
                        - image
            - monai.transforms.CropForegroundd:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
                    source_key: image
            - monai.transforms.Orientationd:
                args: []
                kwargs:
                    axcodes: RAS
                    keys:
                        - image
                        - label
            - monai.transforms.Spacingd:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
                    mode:
                        - bilinear
                        - nearest
                    pixdim:
                        - 1.5
                        - 1.5
                        - 2
            - monai.transforms.SpatialPadd:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
                    spatial_size:
                        - 160
                        - 160
                        - 160
            - monai.transforms.ResizeD:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
                    mode:
                        - trilinear
                        - nearest
                    spatial_size:
                        - 160
                        - 160
                        - 160
        batch_size: 2
        learning_rate: 0.0001
        lr_scheduler: cosine_decay
        max_epochs: 30
        val_batch_size: 1
        val_interval: 5
valid:
    value:
        augmentation:
            - monai.transforms.LoadImaged:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
            - monai.transforms.EnsureChannelFirstd:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
            - monai.transforms.ScaleIntensityRanged:
                args: []
                kwargs:
                    a_max: 164
                    a_min: -57
                    b_max: 1
                    b_min: 0
                    clip: true
                    keys:
                        - image
            - monai.transforms.CropForegroundd:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
                    source_key: image
            - monai.transforms.Orientationd:
                args: []
                kwargs:
                    axcodes: RAS
                    keys:
                        - image
                        - label
            - monai.transforms.Spacingd:
                args: []
                kwargs:
                    keys:
                        - image
                        - label
                    mode:
                        - bilinear
                        - nearest
                    pixdim:
                        - 1.5
                        - 1.5
                        - 2
        roi_size:
            - 160
            - 160
            - 160
        sw_batch_size: 4
wandb:
    value:
        entity_name: marinamusic-queen-s-university
        experiment_name: Calyx_Segmentation_Run1
        log_gradients: true
        project_name: CT_Calyx_Segmentation
